<a href="https://colab.research.google.com/github/fauzia-annisa/project11-credit-card-fraud-detection/blob/main/project11_credit_card_fraud_detectionipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
# distribution of legit transactios & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    25749
1.0       88
Name: count, dtype: int64

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
25833,33785,-0.187402,0.445507,2.199225,3.030535,-0.361376,1.095100,-0.119594,0.245950,-0.371890,...,0.154001,0.813468,0.377732,0.201209,-1.671394,-0.064077,0.067891,0.021521,42.33,0.0
25834,33785,1.237064,0.312096,0.191934,0.496764,-0.129777,-0.551625,-0.007160,-0.048880,-0.240393,...,-0.255114,-0.759423,0.072774,-0.035961,0.238605,0.096858,-0.025772,0.017772,1.79,0.0
25835,33785,1.245292,-0.594493,0.275982,-0.578346,-0.920599,-0.865570,-0.321689,-0.217249,-1.007295,...,0.303333,0.736260,-0.102900,0.452253,0.510125,-0.114928,0.003129,0.021850,70.75,0.0
25836,33787,-0.697373,0.401180,0.803750,-1.015524,-0.226100,0.283660,0.094868,0.077613,-1.327124,...,0.118688,0.467655,-0.162958,-0.703390,-0.174347,-0.202938,-0.369636,-0.152421,49.95,0.0
25837,33787,1.303469,0.498450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25838 entries, 0 to 25837
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    25838 non-null  int64
 1   V1      25838 non-null  float64
 2   V2      25838 non-null  float64
 3   V3      25837 non-null  float64
 4   V4      25837 non-null  float64
 5   V5      25837 non-null  float64
 6   V6      25837 non-null  float64
 7   V7      25837 non-null  float64
 8   V8      25837 non-null  float64
 9   V9      25837 non-null  float64
 10  V10     25837 non-null  float64
 11  V11     25837 non-null  float64
 12  V12     25837 non-null  float64
 13  V13     25837 non-null  float64
 14  V14     25837 non-null  float64
 15  V15     25837 non-null  float64
 16  V16     25837 non-null  float64
 17  V17     25837 non-null  float64
 18  V18     25837 non-null  float64
 19  V19     25837 non-null  float64
 20  V20     25837 non-null  float64
 21  V21     25837 non-null  float64
 22  V22     25837 non-null  float64
 23  V23     25837 non-null  float64
 24  V24     25837 non-null  float64
 25  V25     25837 non-null  float64
 26  V26     25837 non-null  float64
 27  V27     25837 non-null  float64
 28  V28     25837 non-null  float64
 29  Amount  25837 non-null  float64
 30  Class   25837 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.1 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0.0    25749
1.0       88
Name: count, dtype: int64

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(25749, 31)
(88, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    25749.000000
mean        75.726227
std        219.488324
min          0.000000
25%          6.200000
50%         18.960000
75%         67.500000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      88.000000
mean      100.010000
std       265.845031
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,19380.491087,-0.197045,0.145743,0.767372,0.208854,-0.174420,0.088572,-0.100712,0.011278,0.453641,...,0.039986,-0.039570,-0.131409,-0.038716,0.012076,0.128670,0.022883,0.010424,0.003824,75.726227
1.0,17935.875000,-8.613716,6.376169,-12.221731,6.231847,-6.027247,-2.487080,-8.308784,4.351326,-2.987199,...,0.714069,0.539387,-0.381823,-0.350615,-0.252970,0.346695,0.179760,0.856336,0.100578,100.010000

In [ ]:
legit_sample = legit.sample(n=492)

In [ ]:
new_dataset =pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5194,4958,1.138737,0.314065,0.501601,1.293445,-0.123574,-0.410397,0.023003,-0.128692,1.343849,...,-0.284993,-0.611244,0.066572,-0.019828,0.353404,-0.563076,0.000764,0.020593,33.11,0.0
9122,12878,-0.367999,0.777668,1.655693,-0.660604,-0.003070,-0.338665,0.261083,-0.074119,0.851708,...,-0.157964,-0.284271,-0.067961,0.015741,-0.311990,0.814239,-0.203842,-0.006886,5.84,0.0
382,280,0.878794,-0.266909,0.409706,1.509808,-0.487798,0.376829,-0.389288,0.331361,0.702728,...,0.025056,0.110527,-0.191237,-0.059199,0.504350,-0.271526,0.059100,0.053501,109.15,0.0
2252,1791,1.332849,0.389198,-2.165597,-0.306873,2.641351,2.808084,-0.171627,0.683352,-0.297962,...,-0.207432,-0.692417,-0.118598,0.891480,0.730240,0.384013,-0.028465,0.036123,0.76,0.0
11842,20338,-8.438240,4.546631,-6.539248,1.474794,-5.192934,-1.310241,-3.056987,5.301896,0.830521,...,0.102408,-0.241290,-0.344992,0.304194,-0.131121,-0.444110,0.131520,-0.073810,99.99,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
18773,29753,0.269614,3.549755,-5.810353,5.809370,1.538808,-2.269219,-0.824203,0.351070,-3.759059,...,0.371121,-0.322290,-0.549856,-0.520629,1.378210,0.564714,0.553255,0.402400,0.68,1.0
18809,29785,0.923764,0.344048,-2.880004,1.721680,-3.019565,-0.639736,-3.801325,1.299096,0.864065,...,0.899931,1.481271,0.725266,0.176960,-1.815638,-0.536517,0.489035,-0.049729,30.30,1.0
20198,30852,-2.830984,0.885657,1.199930,2.861292,0.321669,0.289966,1.767760,-2.451050,0.069736,...,0.546589,0.334971,0.172106,0.623590,-0.527114,-0.079215,-2.532445,0.311177,104.81,1.0
23308,32686,0.287953,1.728735,-1.652173,3.813544,-1.090927,-0.984745,-2.202318,0.555088,-2.033892,...,0.262202,-0.633528,0.092891,0.187613,0.368708,-0.132474,0.576561,0.309843,0.00,1.0
23422,32745,-2.179135,0.020218,-2.182733,2.572046,-3.663733,0.081568,0.268049,0.660437,-2.374027,...,1.026421,0.299614,1.656800,0.328433,0.106457,0.691775,0.196779,0.241085,717.15,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0     88
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,19326.581301,-0.249878,0.059965,0.651263,0.107815,-0.132717,0.127104,-0.213668,-0.047544,0.535782,...,0.043374,0.068211,-0.141422,-0.053072,-0.002611,0.138072,0.011472,0.023885,0.006637,83.08935
1.0,17935.875000,-8.613716,6.376169,-12.221731,6.231847,-6.027247,-2.487080,-8.308784,4.351326,-2.987199,...,0.714069,0.539387,-0.381823,-0.350615,-0.252970,0.346695,0.179760,0.856336,0.100578,100.01000

In [ ]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
5194    4958  1.138737  0.314065  0.501601  1.293445 -0.123574 -0.410397
9122   12878 -0.367999  0.777668  1.655693 -0.660604 -0.003070 -0.338665
382      280  0.878794 -0.266909  0.409706  1.509808 -0.487798  0.376829
2252    1791  1.332849  0.389198 -2.165597 -0.306873  2.641351  2.808084
11842  20338 -8.438240  4.546631 -6.539248  1.474794 -5.192934 -1.310241
...      ...       ...       ...       ...       ...       ...       ...
18773  29753  0.269614  3.549755 -5.810353  5.809370  1.538808 -2.269219
18809  29785  0.923764  0.344048 -2.880004  1.721680 -3.019565 -0.639736
20198  30852 -2.830984  0.885657  1.199930  2.861292  0.321669  0.289966
23308  32686  0.287953  1.728735 -1.652173  3.813544 -1.090927 -0.984745
23422  32745 -2.179135  0.020218 -2.182733  2.572046 -3.663733  0.081568

             V7        V8        V9  ...       V20       V21       V22  \
5194   0.023003 -0.128692  1.343849  ... -0.183169 -0.284993 -0.611244
9122   0.261083 -0.074119  0.851708  ... -0.005514 -0.157964 -0.284271
382   -0.389288  0.331361  0.702728  ... -0.001708  0.025056  0.110527
2252  -0.171627  0.683352 -0.297962  ...  0.053607 -0.207432 -0.692417
11842 -3.056987  5.301896  0.830521  ... -0.074068  0.102408 -0.241290
...         ...       ...       ...  ...       ...       ...       ...
18773 -0.824203  0.351070 -3.759059  ...  0.310525  0.371121 -0.322290
18809 -3.801325  1.299096  0.864065  ...  0.170872  0.899931  1.481271
20198  1.767760 -2.451050  0.069736  ... -1.016923  0.546589  0.334971
23308 -2.202318  0.555088 -2.033892  ...  0.265250  0.262202 -0.633528
23422  0.268049  0.660437 -2.374027  ...  1.957960  1.026421  0.299614

            V23       V24       V25       V26       V27       V28  Amount
5194   0.066572 -0.019828  0.353404 -0.563076  0.000764  0.020593   33.11
9122  -0.067961  0.015741 -0.311990  0.814239 -0.203842 -0.006886    5.84
382   -0.191237 -0.059199  0.504350 -0.271526  0.059100  0.053501  109.15
2252  -0.118598  0.891480  0.730240  0.384013 -0.028465  0.036123    0.76
11842 -0.344992  0.304194 -0.131121 -0.444110  0.131520 -0.073810   99.99
...         ...       ...       ...       ...       ...       ...     ...
18773 -0.549856 -0.520629  1.378210  0.564714  0.553255  0.402400    0.68
18809  0.725266  0.176960 -1.815638 -0.536517  0.489035 -0.049729   30.30
20198  0.172106  0.623590 -0.527114 -0.079215 -2.532445  0.311177  104.81
23308  0.092891  0.187613  0.368708 -0.132474  0.576561  0.309843    0.00
23422  1.656800  0.328433  0.106457  0.691775  0.196779  0.241085  717.15

[580 rows x 30 columns]

In [ ]:
print(Y)

5194     0.0
9122     0.0
382      0.0
2252     0.0
11842    0.0
        ...
18773    1.0
18809    1.0
20198    1.0
23308    1.0
23422    1.0
Name: Class, Length: 580, dtype: float64

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(580, 30) (464, 30) (116, 30)

In [ ]:
model = LogisticRegression()

In [ ]:
# training the logistix Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [35]:
print('Accuracy on Training data :', training_data_accuracy)

Accuracy on Training data : 0.9806034482758621

In [36]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [37]:
print('Accuracy score on test data :', test_data_accuracy)

Accuracy score on test data : 0.9913793103448276